Slackclient app
GrafeasGroup/tor_core pull request #12
Opened 2017-11-21 01:47 UTC by NGTmeaty

This should be completing #11. It should move from webhooks to slackclient.

2017-11-21 03:25 UTC, perryprog requested changes
Can you change the first two commit messages so they are different, or squash them?

2017-11-21 03:25 UTC, perryprog commented on tor_core/helpers.py
> +def send_to_slack(message, config,  channel="#general"):
Extra whitespace here

2017-11-21 03:26 UTC, perryprog commented on tor_core/helpers.py
> +def send_to_slack(message, config,  channel="#general"):
Oh, there's also double quotes instead of single quotes here.

2017-11-21 03:26 UTC, perryprog requested changes

2017-11-21 03:26 UTC, perryprog commented on tor_core/helpers.py
> +            "chat.postMessage",
Double quotes instead of single quotes here again

2017-11-21 19:29 UTC, itsthejoker commented on tor_core/helpers.py
> +    :param channel: channel option, defaults to general
Let's add in that this should be a string as well -- we're not going full-on type hinting, but I like to have it in the docstrings.

2017-11-21 19:41 UTC, itsthejoker commented
Overall it looks good -- let's change the double quotes to single quotes and we'll test. I don't really care about the doubled up commit messages; just something to watch out for in the future.

2017-11-21 19:47 UTC, NGTmeaty commented
Changes should be made.

2017-11-21 20:07 UTC, perryprog requested changes

2017-11-21 20:07 UTC, perryprog commented on tor_core/helpers.py
> +def send_to_slack(message, config,  channel='#general'):
There is still whitespace here ):

2017-11-22 01:50 UTC, perryprog approved these changes
LGTM

2017-11-22 02:34 UTC, itsthejoker approved these changes

2017-11-22 02:35 UTC, merged

2017-11-22 05:09 UTC, TheLonelyGhost commented on tor_core/helpers.py
> +def send_to_slack(message, config, channel='#general'):
Just came in to comment, this is a beautiful way of retaining backwards compatibility despite a lot of added functionality. Very nice job!